import Head from 'next/head'
import { 
  AppBar,
  Toolbar,
  Typography,
  Drawer,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  CssBaseline,
} from '@material-ui/core';
import { Archive, Person, TableChart } from '@material-ui/icons';
import React from 'react';
import useStyles from '../../hooks/useStyles'
import { useRouter } from 'next/router';

type BasePageProps = {
  children: React.ReactNode,
  pageName: string
}

function BasePage({children, pageName}:BasePageProps) {
  const classes = useStyles();
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📁</text></svg>"/>
      </Head>
      <div className={classes.root}>
        <CssBaseline />
        <AppBar position="fixed" className={classes.appBar}>
          <Toolbar>
            <Typography variant="h6" noWrap>
              {pageName}
            </Typography>
          </Toolbar>
        </AppBar>
        <Drawer
          className={classes.drawer}
          variant="permanent"
          classes={{
            paper: classes.drawerPaper,
          }}
        >
          <Toolbar />
          <div className={classes.drawerContainer}>
            <List>
                <ListItem button onClick={() => router.push('/')} >
                  <ListItemIcon><TableChart/></ListItemIcon>
                  <ListItemText primary='All Projects'/>
                </ListItem>
                <ListItem button onClick={() => router.push('/project/new')} >
                  <ListItemIcon><Archive /></ListItemIcon>
                  <ListItemText primary='New Project'/>
                </ListItem>
                <ListItem button onClick={() => router.push('/user/new')}>
                  <ListItemIcon><Person /></ListItemIcon>
                  <ListItemText primary='New User' />
                </ListItem>
            </List>            
          </div>
        </Drawer>
        <main className={classes.content}>
          <Toolbar />
          {children}
        </main>
      </div>
    </div>
)
}

export default BasePage
